import { Config } from 'wikiparser-node';

export const bikiConfig: Config = {
    ext: [
        'nowiki',
        'pre',
        'gallery',
        'indicator',
        'poem',
        'ref',
        'references',
        'categorytree',
        'charinsert',
        'imagemap',
        'inputbox',
        'templatestyles',
        'score',
        'ce',
        'chem',
        'graph',
        'hiero',
        'langconvert',
        'mapframe',
        'maplink',
        'math',
        'phonos',
        'section',
        'source',
        'syntaxhighlight',
        'templatedata',
        'timeline',
        'sqf',
    ],
    html: [
        [
            'b',
            'bdi',
            'del',
            'i',
            'ins',
            'u',
            'font',
            'big',
            'small',
            'sub',
            'sup',
            'h1',
            'h2',
            'h3',
            'h4',
            'h5',
            'h6',
            'cite',
            'code',
            'em',
            's',
            'strike',
            'strong',
            'tt',
            'var',
            'div',
            'center',
            'blockquote',
            'ol',
            'ul',
            'dl',
            'table',
            'caption',
            'pre',
            'sqf',
            'ruby',
            'rb',
            'rp',
            'rt',
            'rtc',
            'p',
            'span',
            'abbr',
            'dfn',
            'kbd',
            'samp',
            'data',
            'time',
            'mark',
            'tr',
            'td',
            'th',
            'q',
            'bdo',
        ],
        ['li', 'dt', 'dd'],
        ['br', 'wbr', 'hr', 'meta', 'link'],
    ],
    namespaces: {
        '-2': 'Media',
        '-1': 'Special',
        '0': '',
        '1': 'Talk',
        '2': 'User',
        '3': 'User talk',
        '4': 'Project',
        '5': 'Project talk',
        '6': 'File',
        '7': 'File talk',
        '8': 'MediaWiki',
        '9': 'MediaWiki talk',
        '10': 'Template',
        '11': 'Template talk',
        '12': 'Help',
        '13': 'Help talk',
        '14': 'Category',
        '15': 'Category talk',
        '100': 'Portal',
        '101': 'Portal talk',
        '118': 'Draft',
        '119': 'Draft talk',
        '710': 'TimedText',
        '711': 'TimedText talk',
        '828': 'Module',
        '829': 'Module talk',
        '2300': 'Gadget',
        '2301': 'Gadget talk',
        '2302': 'Gadget definition',
        '2303': 'Gadget definition talk',
    },
    nsid: {
        '': 0,
        media: -2,
        special: -1,
        talk: 1,
        user: 2,
        'user talk': 3,
        wp: 4,
        wikipedia: 4,
        project: 4,
        wt: 5,
        'wikipedia talk': 5,
        'project talk': 5,
        file: 6,
        image: 6,
        'file talk': 7,
        'image talk': 7,
        mediawiki: 8,
        'mediawiki talk': 9,
        template: 10,
        'template talk': 11,
        help: 12,
        'help talk': 13,
        category: 14,
        'category talk': 15,
        portal: 100,
        'portal talk': 101,
        draft: 118,
        'draft talk': 119,
        timedtext: 710,
        'timedtext talk': 711,
        module: 828,
        'module talk': 829,
        gadget: 2300,
        'gadget talk': 2301,
        'gadget definition': 2302,
        'gadget definition talk': 2303,
    },
    parserFunction: [
        {
            ns: 'ns',
            nse: 'nse',
            urlencode: 'urlencode',
            lcfirst: 'lcfirst',
            ucfirst: 'ucfirst',
            lc: 'lc',
            uc: 'uc',
            localurl: 'localurl',
            localurle: 'localurle',
            fullurl: 'fullurl',
            fullurle: 'fullurle',
            canonicalurl: 'canonicalurl',
            canonicalurle: 'canonicalurle',
            formatnum: 'formatnum',
            grammar: 'grammar',
            gender: 'gender',
            plural: 'plural',
            bidi: 'bidi',
            '#language': 'language',
            padleft: 'padleft',
            padright: 'padright',
            anchorencode: 'anchorencode',
            filepath: 'filepath',
            pageid: 'pageid',
            int: 'int',
            '#special': 'special',
            '#speciale': 'speciale',
            '#tag': 'tag',
            '#formatdate': 'formatdate',
            '#dateformat': 'formatdate',
            '#invoke': 'invoke',
            '#if': 'if',
            '#ifeq': 'ifeq',
            '#switch': 'switch',
            '#ifexist': 'ifexist',
            '#ifexpr': 'ifexpr',
            '#iferror': 'iferror',
            '#time': 'time',
            '#timel': 'timel',
            '#expr': 'expr',
            '#rel2abs': 'rel2abs',
            '#titleparts': 'titleparts',
            pendingchangelevel: 'pendingchangelevel',
            '#categorytree': 'categorytree',
            articlepath: 'articlepath',
            server: 'server',
            servername: 'servername',
            scriptpath: 'scriptpath',
            stylepath: 'stylepath',
            msgnw: 'msgnw',
            '#related': 'related',
            '#babel': 'babel',
            '#commaseparatedlist': 'commaseparatedlist',
            '#coordinates': 'coordinates',
            '#lst': 'lst',
            '#lsth': 'lsth',
            '#lstx': 'lstx',
            '#assessment': 'assessment',
            '#mentor': 'mentor',
            '#property': 'property',
            '#target': 'target',
            '#section': 'section',
            '#section-x': 'section-x',
            '#section-h': 'section-h',
            noexternallanglinks: 'noexternallanglinks',
            '#statements': 'statements',
            numberofwikis: 'numberofwikis',
            wbreponame: 'wbreponame',
        },
        [
            'NUMBEROFPAGES',
            'NUMBEROFUSERS',
            'NUMBEROFACTIVEUSERS',
            'NUMBEROFARTICLES',
            'NUMBEROFFILES',
            'NUMBEROFADMINS',
            'NUMBERINGROUP',
            'NUMINGROUP',
            'NUMBEROFEDITS',
            'DEFAULTSORT',
            'DEFAULTSORTKEY',
            'DEFAULTCATEGORYSORT',
            'PAGESINCATEGORY',
            'PAGESINCAT',
            'PAGESIZE',
            'PROTECTIONLEVEL',
            'PROTECTIONEXPIRY',
            'NAMESPACEE',
            'NAMESPACENUMBER',
            'TALKSPACE',
            'TALKSPACEE',
            'SUBJECTSPACE',
            'ARTICLESPACE',
            'SUBJECTSPACEE',
            'ARTICLESPACEE',
            'PAGENAME',
            'PAGENAMEE',
            'FULLPAGENAME',
            'FULLPAGENAMEE',
            'ROOTPAGENAME',
            'ROOTPAGENAMEE',
            'BASEPAGENAME',
            'BASEPAGENAMEE',
            'SUBPAGENAME',
            'SUBPAGENAMEE',
            'TALKPAGENAME',
            'TALKPAGENAMEE',
            'SUBJECTPAGENAME',
            'ARTICLEPAGENAME',
            'SUBJECTPAGENAMEE',
            'ARTICLEPAGENAMEE',
            'REVISIONID',
            'REVISIONDAY',
            'REVISIONDAY2',
            'REVISIONMONTH',
            'REVISIONMONTH1',
            'REVISIONYEAR',
            'REVISIONTIMESTAMP',
            'REVISIONUSER',
            'CASCADINGSOURCES',
            'NAMESPACE',
            'DISPLAYTITLE',
            'SHORTDESC',
            '!',
            'CURRENTMONTH',
            'CURRENTMONTH2',
            'CURRENTMONTH1',
            'CURRENTMONTHNAME',
            'CURRENTMONTHNAMEGEN',
            'CURRENTMONTHABBREV',
            'CURRENTDAY',
            'CURRENTDAY2',
            'CURRENTDAYNAME',
            'CURRENTYEAR',
            'CURRENTTIME',
            'CURRENTHOUR',
            'LOCALMONTH',
            'LOCALMONTH2',
            'LOCALMONTH1',
            'LOCALMONTHNAME',
            'LOCALMONTHNAMEGEN',
            'LOCALMONTHABBREV',
            'LOCALDAY',
            'LOCALDAY2',
            'LOCALDAYNAME',
            'LOCALYEAR',
            'LOCALTIME',
            'LOCALHOUR',
            'SITENAME',
            'CURRENTWEEK',
            'CURRENTDOW',
            'LOCALWEEK',
            'LOCALDOW',
            'REVISIONSIZE',
            'CURRENTVERSION',
            'CURRENTTIMESTAMP',
            'LOCALTIMESTAMP',
            'DIRECTIONMARK',
            'DIRMARK',
            'CONTENTLANGUAGE',
            'CONTENTLANG',
            'PAGELANGUAGE',
            '=',
        ],
        ['msg', 'raw'],
        ['subst', 'safesubst'],
    ],
    doubleUnderscore: [
        [
            'forcetoc',
            'nocc',
            'nocontentconvert',
            'noeditsection',
            'nogallery',
            'notc',
            'notitleconvert',
            'notoc',
            'toc',
            'archivedtalk',
            'notalk',
        ],
        [
            'EXPECTUNUSEDCATEGORY',
            'DISAMBIG',
            'HIDDENCAT',
            'INDEX',
            'NEWSECTIONLINK',
            'NOINDEX',
            'NONEWSECTIONLINK',
            'STATICREDIRECT',
            'NOGLOBAL',
            'EXPECTED_UNCONNECTED_PAGE',
        ],
    ],
    protocol:
		'bitcoin:|ftp://|ftps://|geo:|git://|gopher://|http://|https://|irc://|ircs://|magnet:|mailto:|mms://|news:|nntp://|redis://|sftp://|sip:|sips:|sms:|ssh://|svn://|tel:|telnet://|urn:|worldwind://|xmpp:',
    interwiki: [
        'acronym',
        'advisory',
        'advogato',
        'aew',
        'antwiki',
        'appropedia',
        'aquariumwiki',
        'arborwiki',
        'arxiv',
        'baden',
        'battlestarwiki',
        'bcnbio',
        'beacha',
        'betawiki',
        'bibcode',
        'bibliowiki',
        'bluwiki',
        'botwiki',
        'boxrec',
        'bugzilla',
        'bulba',
        'c',
        'c2',
        'c2find',
        'cache',
        'ĉej',
        'centralwikia',
        'chej',
        'choralwiki',
        'citizendium',
        'commons',
        'communityscheme',
        'communitywiki',
        'comune',
        'creativecommons',
        'creativecommonswiki',
        'cxej',
        'dcc',
        'dcdatabase',
        'dcma',
        'debian',
        'devmo',
        'dico',
        'dicoado',
        'dictionary',
        'dict',
        'discord',
        'disinfopedia',
        'distributedproofreaders',
        'distributedproofreadersca',
        'dmoz',
        'dmozs',
        'doi',
        'donate',
        'doom_wiki',
        'download',
        'dbdump',
        'dpd',
        'dpla',
        'drae',
        'dreamhost',
        'drumcorpswiki',
        'dwjwiki',
        'ecoreality',
        'elibre',
        'emacswiki',
        'encyc',
        'energiewiki',
        'englyphwiki',
        'enkol',
        'eokulturcentro',
        'esolang',
        'etherpad',
        'ethnologue',
        'ethnologuefamily',
        'exotica',
        'exkcd',
        'fanimutationwiki',
        'fedora',
        'finalfantasy',
        'finnix',
        'flickruser',
        'flickrphoto',
        'floralwiki',
        'foldoc',
        'foundation',
        'foundationsite',
        'foxwiki',
        'freebio',
        'freebsdman',
        'freeculturewiki',
        'freedomdefined',
        'freekiwiki',
        'freenode',
        'freesoft',
        'ganfyd',
        'gardenology',
        'gausswiki',
        'gentoo',
        'genwiki',
        'gerrit',
        'git',
        'gitlab',
        'globalcontribs',
        'glottolog',
        'glottopedia',
        'google',
        'googledefine',
        'googlegroups',
        'guildwarswiki',
        'guildwiki',
        'gucprefix',
        'gutenberg',
        'gutenbergwiki',
        'hackerspaces',
        'hammondwiki',
        'hdl',
        'heraldik',
        'horizonlabs',
        'hrwiki',
        'hrfwiki',
        'hupwiki',
        'iarchive',
        'imdbname',
        'imdbtitle',
        'imdbcompany',
        'incubator',
        'infosphere',
        'irc',
        'ircs',
        'ircrc',
        'rcirc',
        'iso639-3',
        'issn',
        'iuridictum',
        'jaglyphwiki',
        'jefo',
        'jerseydatabase',
        'jira',
        'jspwiki',
        'jstor',
        'kamelo',
        'karlsruhe',
        'kinowiki',
        'komicawiki',
        'kontuwiki',
        'lexemes',
        'liberachat',
        'libreplanet',
        'lingualibre',
        'linguistlist',
        'linuxwiki',
        'linuxwikide',
        'listarchive',
        'liswiki',
        'literateprograms',
        'livepedia',
        'localwiki',
        'lojban',
        'lokalhistoriewiki',
        'lostpedia',
        'lqwiki',
        'luxo',
        'mail',
        'mailarchive',
        'mariowiki',
        'marveldatabase',
        'meatball',
        'mw',
        'mediazilla',
        'memoryalpha',
        'metawiki',
        'metawikimedia',
        'metawikipedia',
        'mineralienatlas',
        'mixnmatch',
        'moinmoin',
        'monstropedia',
        'mosapedia',
        'mozcom',
        'mozillawiki',
        'mozillazinekb',
        'musicbrainz',
        'mediawikiwiki',
        'mwod',
        'mwot',
        'nkcells',
        'nlab',
        'nara',
        'nosmoke',
        'nost',
        'nostalgia',
        'oeis',
        'oldwikisource',
        'olpc',
        'omegawiki',
        'onelook',
        'openlibrary',
        'openstreetmap',
        'openwetware',
        'organicdesign',
        'orthodoxwiki',
        'osmwiki',
        'otrs',
        'otrswiki',
        'ourmedia',
        'outreach',
        'outreachwiki',
        'owasp',
        'panawiki',
        'patwiki',
        'paws',
        'personaltelco',
        'petscan',
        'phab',
        'phabricator',
        'phwiki',
        'phpwiki',
        'planetmath',
        'pmeg',
        'pmid',
        'pokewiki',
        'pokéwiki',
        'policy',
        'proofwiki',
        'pyrev',
        'pythoninfo',
        'pythonwiki',
        'pywiki',
        'quality',
        'quarry',
        'regiowiki',
        'rev',
        'revo',
        'rfc',
        'rheinneckar',
        'robowiki',
        'rodovid',
        'rowiki',
        'rt',
        's23wiki',
        'scholar',
        'schoolswp',
        'scores',
        'scoutwiki',
        'scramble',
        'seattlewiki',
        'slwiki',
        'semantic-mw',
        'senseislibrary',
        'sep11',
        'sharemap',
        'silcode',
        'slashdot',
        'sourceforge',
        'spcom',
        'species',
        'squeak',
        'stats',
        'stewardry',
        'strategy',
        'strategywiki',
        'sulutil',
        'swtrain',
        'svn',
        'swinbrain',
        'tabwiki',
        'tclerswiki',
        'technorati',
        'tenwiki',
        'testwiki',
        'testwikidata',
        'test2wiki',
        'tfwiki',
        'thelemapedia',
        'theopedia',
        'thinkwiki',
        'ticket',
        'tmbw',
        'tmnet',
        'tmwiki',
        'toolforge',
        'toolhub',
        'toollabs',
        'tools',
        'tswiki',
        'translatewiki',
        'tviv',
        'twiki',
        'twl',
        'tyvawiki',
        'umap',
        'uncyclopedia',
        'unihan',
        'unreal',
        'urbandict',
        'usej',
        'usemod',
        'usability',
        'utrs',
        'vikidia',
        'viaf',
        'vlos',
        'vkol',
        'votewiki',
        'vrtwiki',
        'vrts',
        'weirdgloop',
        'werelate',
        'wg',
        'wikia',
        'wikiasite',
        'wikiapiary',
        'wikibooks',
        'wikichristian',
        'wikicities',
        'wikicity',
        'wikiconference',
        'wikidata',
        'wikiedudashboard',
        'wikif1',
        'wikifunctions',
        'wikifur',
        'wikihow',
        'wikiindex',
        'wikilivres',
        'wikilivresru',
        'wikimac-de',
        'wikimedia',
        'wikinews',
        'wikinfo',
        'wikinvest',
        'wikiotics',
        'wikipapers',
        'wikipedia',
        'wikipediawikipedia',
        'wikiquote',
        'wikisophia',
        'wikisource',
        'wikisp',
        'wikispecies',
        'wikispot',
        'wikiskripta',
        'wikitech',
        'labsconsole',
        'wikiti',
        'wikiversity',
        'wikivoyage',
        'betawikiversity',
        'wikiwikiweb',
        'wiktionary',
        'wlug',
        'wmam',
        'wmar',
        'wmat',
        'wmau',
        'wmbd',
        'wmbe',
        'wmbr',
        'wmca',
        'wmch',
        'wmcl',
        'wmcn',
        'wmco',
        'wmcz',
        'wmcz_docs',
        'wmcz_old',
        'wmdc',
        'securewikidc',
        'wmde',
        'wmdk',
        'wmdoc',
        'wmee',
        'wmec',
        'wmes',
        'wmet',
        'wmfdashboard',
        'wmfi',
        'wmfr',
        'wmge',
        'wmhi',
        'wmhk',
        'wmhu',
        'wmid',
        'wmil',
        'wmin',
        'wmit',
        'wmke',
        'wmmk',
        'wmmx',
        'wmnl',
        'wmnyc',
        'wmno',
        'wmpa-us',
        'wmph',
        'wmpl',
        'wmplsite',
        'wmpt',
        'wmpunjabi',
        'wmromd',
        'wmrs',
        'wmru',
        'wmse',
        'wmsk',
        'wmtr',
        'wmtw',
        'wmua',
        'wmuk',
        'wmve',
        'wmza',
        'wm2005',
        'wm2006',
        'wm2007',
        'wm2008',
        'wm2009',
        'wm2010',
        'wm2011',
        'wm2012',
        'wm2013',
        'wm2014',
        'wm2015',
        'wm2016',
        'wm2017',
        'wm2018',
        'wmania',
        'wikimania',
        'wikispore',
        'wmteam',
        'wmf',
        'wmfblog',
        'wmdeblog',
        'wookieepedia',
        'wowwiki',
        'wqy',
        'wurmpedia',
        'xkcd',
        'xtools',
        'zum',
        'zwiki',
        'm',
        'meta',
        'd',
        'f',
        'ak',
        'cz',
        'dk',
        'epo',
        'jp',
        'cmn',
        'w',
        'wikt',
        'q',
        'b',
        'n',
        's',
        'chapter',
        'v',
        'voy',
        'aa',
        'ab',
        'ace',
        'ady',
        'af',
        'als',
        'alt',
        'am',
        'ami',
        'an',
        'ang',
        'anp',
        'ar',
        'arc',
        'ary',
        'arz',
        'as',
        'ast',
        'atj',
        'av',
        'avk',
        'awa',
        'ay',
        'az',
        'azb',
        'ba',
        'ban',
        'bar',
        'bat-smg',
        'bbc',
        'bcl',
        'be',
        'be-tarask',
        'be-x-old',
        'bg',
        'bh',
        'bi',
        'bjn',
        'blk',
        'bm',
        'bn',
        'bo',
        'bpy',
        'br',
        'bs',
        'btm',
        'bug',
        'bxr',
        'ca',
        'cbk-zam',
        'cdo',
        'ce',
        'ceb',
        'ch',
        'cho',
        'chr',
        'chy',
        'ckb',
        'co',
        'cr',
        'crh',
        'cs',
        'csb',
        'cu',
        'cv',
        'cy',
        'da',
        'dag',
        'de',
        'dga',
        'din',
        'diq',
        'dsb',
        'dty',
        'dv',
        'dz',
        'ee',
        'el',
        'eml',
        'en',
        'eo',
        'es',
        'et',
        'eu',
        'ext',
        'fa',
        'fat',
        'ff',
        'fi',
        'fiu-vro',
        'fj',
        'fo',
        'fon',
        'fr',
        'frp',
        'frr',
        'fur',
        'fy',
        'ga',
        'gag',
        'gan',
        'gcr',
        'gd',
        'gl',
        'glk',
        'gn',
        'gom',
        'gor',
        'got',
        'gpe',
        'gsw',
        'gu',
        'guc',
        'gur',
        'guw',
        'gv',
        'ha',
        'hak',
        'haw',
        'he',
        'hi',
        'hif',
        'ho',
        'hr',
        'hsb',
        'ht',
        'hu',
        'hy',
        'hyw',
        'hz',
        'ia',
        'id',
        'ie',
        'ig',
        'ii',
        'ik',
        'ilo',
        'inh',
        'io',
        'is',
        'it',
        'iu',
        'ja',
        'jam',
        'jbo',
        'jv',
        'ka',
        'kaa',
        'kab',
        'kbd',
        'kbp',
        'kcg',
        'kg',
        'ki',
        'kj',
        'kk',
        'kl',
        'km',
        'kn',
        'ko',
        'koi',
        'kr',
        'krc',
        'ks',
        'ksh',
        'ku',
        'kv',
        'kw',
        'ky',
        'la',
        'lad',
        'lb',
        'lbe',
        'lez',
        'lfn',
        'lg',
        'li',
        'lij',
        'lld',
        'lmo',
        'ln',
        'lo',
        'lrc',
        'lt',
        'ltg',
        'lv',
        'lzh',
        'mad',
        'mai',
        'map-bms',
        'mdf',
        'mg',
        'mh',
        'mhr',
        'mi',
        'min',
        'mk',
        'ml',
        'mn',
        'mni',
        'mnw',
        'mo',
        'mr',
        'mrj',
        'ms',
        'mt',
        'mus',
        'mwl',
        'my',
        'myv',
        'mzn',
        'na',
        'nah',
        'nan',
        'nap',
        'nds',
        'nds-nl',
        'ne',
        'new',
        'ng',
        'nia',
        'nl',
        'nn',
        'no',
        'nov',
        'nqo',
        'nrm',
        'nso',
        'nv',
        'ny',
        'oc',
        'olo',
        'om',
        'or',
        'os',
        'pa',
        'pag',
        'pam',
        'pap',
        'pcd',
        'pcm',
        'pdc',
        'pfl',
        'pi',
        'pih',
        'pl',
        'pms',
        'pnb',
        'pnt',
        'ps',
        'pt',
        'pwn',
        'qu',
        'rm',
        'rmy',
        'rn',
        'ro',
        'roa-rup',
        'roa-tara',
        'ru',
        'rue',
        'rup',
        'rw',
        'sa',
        'sah',
        'sat',
        'sc',
        'scn',
        'sco',
        'sd',
        'se',
        'sg',
        'sgs',
        'sh',
        'shi',
        'shn',
        'shy',
        'si',
        'simple',
        'sk',
        'skr',
        'sl',
        'sm',
        'smn',
        'sn',
        'so',
        'sq',
        'sr',
        'srn',
        'ss',
        'st',
        'stq',
        'su',
        'sv',
        'sw',
        'szl',
        'szy',
        'ta',
        'tay',
        'tcy',
        'te',
        'tet',
        'tg',
        'th',
        'ti',
        'tk',
        'tl',
        'tly',
        'tn',
        'to',
        'tpi',
        'tr',
        'trv',
        'ts',
        'tt',
        'tum',
        'tw',
        'ty',
        'tyv',
        'udm',
        'ug',
        'uk',
        'ur',
        'uz',
        've',
        'vec',
        'vep',
        'vi',
        'vls',
        'vo',
        'vro',
        'wa',
        'war',
        'wo',
        'wuu',
        'xal',
        'xh',
        'xmf',
        'yi',
        'yo',
        'yue',
        'za',
        'zea',
        'zgh',
        'zh',
        'zh-classical',
        'zh-min-nan',
        'zh-yue',
        'zu',
        'zh-cn',
        'zh-tw',
        'egl',
        'en-simple',
        'nb',
    ],
    img: {
        thumbnail: 'thumbnail',
        thumb: 'thumbnail',
        'thumbnail=$1': 'manualthumb',
        'thumb=$1': 'manualthumb',
        left: 'left',
        right: 'right',
        none: 'none',
        $1px: 'width',
        center: 'center',
        centre: 'center',
        framed: 'framed',
        enframed: 'framed',
        frame: 'framed',
        frameless: 'frameless',
        upright: 'upright',
        'upright=$1': 'manual-upright',
        'upright $1': 'manual-upright',
        border: 'border',
        'alt=$1': 'alt',
        'class=$1': 'class',
        'link=$1': 'link',
        baseline: 'baseline',
        sub: 'sub',
        super: 'super',
        sup: 'super',
        top: 'top',
        'text-top': 'text-top',
        middle: 'middle',
        bottom: 'bottom',
        'text-bottom': 'text-bottom',
        'lang=$1': 'lang',
        'page=$1': 'page',
        'page $1': 'page',
        'lossy=$1': 'lossy',
    },
    variants: [],
};
