name: SQFLint-VSCode CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      # SQFLint build disabled for now
      #  with:
      #    submodules: 'recursive'
      #- name: Build SQFLint with Docker image
      #  uses: ./sqflint/.github/actions/sqflint-build-action
      #  env:
      #    ANT_BUILD_DIR: sqflint
     
      - name: Use Node.js 14.19.1
        uses: actions/setup-node@v3
        with:
          node-version: 14.19.1
          cache: npm

      - name: Install latest NPM
        run: npm i -g npm@latest

      - name: Build package
        run: npm run package
    
      - name: Store vsix
        uses: actions/upload-artifact@v2
        with:
          name: sqflint
          path: sqflint-*.vsix